export const ReduxConstants = {
    COUNT_INCRESE: 'COUNT_INCRESE',
    COUNT_DECRESE: 'COUNT_DECRESE',
    COUNT_INCRESE: 'COUNT_INCRESE',
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    GET_DATA: 'GET_DATA',
    FETCH_REQUEST_BEGIN: 'FETCH_REQUEST_BEGIN',
    FETCH_REQUEST_FAILED: 'FETCH_REQUEST_FAILED'
}