export const Strings = {
    onBoarding: {
        welcome: 'Welcome \n to our store',
        getGroceryText: 'Ger your groceries in as fast as one hour',
    },
    signInScreen: {
        getGrocery: 'Get your groceries \nwith nectar',
        socialMedia: 'Or connect with social media',
        countinueWithGoogle: 'Continue With Google',
        continueWithFacebook: 'Continue With Facebook'
    },
    verificationScreen: {
        enterCode: 'Enter your 4-digit code',
        code: 'Code',
        resendCode: 'Resend Code',
    },
    selectLocationScreen: {
        selectLocation: 'Select Your Location',
        text: 'Swithch on your location to stay in tune with \n what’s happening in your area',
        zone: 'Your Zone',
        area: 'Your Area',
        submit: 'Submit'
    },
    loginScreen: {
        loging: 'Loging',
        enter: 'Enter your emails and password',
        email: 'Email',
        password: 'Password',
        forgotPassword: 'Forgot Password?',
        dontHaveAccount: 'Don’t have an account?',
        singUp: ' Sign Up',
        logIn: ' Log In',
    },
    signUpScreen: {
        enterCredential: 'Enter your credentials to continue',
        username: 'UserName',
        agree: 'By continuing you agree to our',
        terms: 'Terms of Service',
        policy: 'Privacy Policy.',
        alreadyHaveAccount: 'Already have an account?'
    },
    HomeScreen: {
        city: 'Dhaka, Banassre',
        searchStore: 'Search Store',
        exclusiveOffer: 'Exclusive Offer',
        seeAll: 'See all',
        banana: 'Organic Bananas',
        banana_quantity: '7pcs, Priceg',
        banana_price: 4.99,
        apple: 'Red Apple',
        apple_quantity: '1kg, Priceg',
        apple_price: 4.99,
        grapes: 'Grapes',
        grapes_quantity: '1Kg, Priceg',
        grapes_price: 4.99,
        best_selling: 'Best Selling',
        capsicum: 'Bell Pepper Red',
        capsicum_quantity: '1kg, Price',
        capsicum_price: 4.99,
        ginger: 'Ginger',
        ginger_quantity: '250gm, Price',
        ginger_price: 2.99,
        greenchili: 'Green Chili',
        greenchili_quantity: '500gm, Price',
        greenchili_price: 2.99,
        groceries: 'Groceries',
        beefbone: 'Beef Bone',
        beefbone_quantity: '1kg, Priceg',
        beefbone_price: 4.99,
        broilerchicken: 'Broiler Chicken',
        broilerchicken_quantity: '1kg, Priceg',
        broilerchicken_price: 4.99,
        pulses: 'Pulses',
        rice: 'Rice',
    },
    bottomTab: {
        Shop: 'Shop',
        Explore: 'Explore',
        Cart: 'Cart',
        Favourite: 'Favourite',
        Account: 'Account',
    },
    ProductDetailScreen: {
        naturel_red_apple: 'Naturel Red Apple',
        product_detail: 'Product Detail',
        apple_description: 'Apples are nutritious. Apples may be good for weight loss. apples may be good for your heart. As part of a healtful and varied diet.',
        nutritions: 'Nutritions',
        gr: '100gr',
        review: 'Review',
        Add_to_basket: 'Add To Basket',
        banana_description: 'A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. ',
        grapes_description: 'Grapes are a type of fruit that grow in clusters of 15 to 300, and can be crimson, black, dark blue, yellow, green, orange, and pink.',
        banana_nutrition: 'one medium ripe banana, provides about 110 calories, 0 gram fat, 1 gram protein, 28 grams carbohydrate, 15 grams sugar (naturally occurring), 3 grams fiber, and 450 mg potassium.'
    },
    exploreScreen: {
        findproducts: 'Find Products',
        Fruits: 'Frash Fruits\n& Vegetable',
        cookingOil: 'Cooking Oil\n& Ghee',
        meat: 'Meat & Fish',
        bakery: 'Bakery & Snacks',
        dairy: 'Dairy & Eggs',
        beverages: 'Beverages',
    },
    beverages: {
        coke: 'Diet Coke',
        coke_quantity: '355ml, Price',
        coke_price: 1.99,
        sprite: 'Sprite Can',
        sprite_quantity: '325ml, Price',
        sprite_price: 1.50,
        apple_grape_juice: 'Apple & Grape\nJuice',
        apple_grape_juice_quantity: '2L, Price',
        apple_grape_juice_price: 15.99,
        orengejuice: 'Orenge Juice',
        orengejuice_quantity: '2L, Price',
        orengejuice_price: 15.99,
        cocacola: 'Coca Cola Can',
        cocacola_quantity: '325ml, Price',
        cocacola_price: 4.99,
        pepsi: 'Pepsi Can ',
        pepsi_quantity: '330ml, Price',
        pepsi_price: 4.99,
    },
    eggItems: {
        egg_chicken_red: 'Egg Chicken Red',
        egg_chicken_red_quantity: '4pcs, Price',
        egg_chicken_red_price: 1.99,
        egg_chicken_white: 'Egg Chicken White',
        egg_chicken_white_quantity: '180g, Price',
        egg_chicken_white_price: 1.50,
        egg_pasta: 'Egg Pasta',
        egg_pasta_quantity: '30gm, Price',
        egg_pasta_price: 15.99,
        egg_noodles: 'Egg Noodles',
        egg_noodles_quantity: '2L, Price',
        egg_noodles_price: 15.99,
        eggless_mayonnaise: 'Mayonnaise Eggless',
        eggless_mayonnaise_quantity: '200gm, Price',
        eggless_mayonnaise_price: 15.99,
    },
    filterScreen: {
        filters: 'Filters',
        categories: 'Categories',
        eggs: 'Eggs',
        noodles_pasta: 'Noodles & Pasta',
        chips_crisps: 'Chips & Crisps',
        fastfood: 'Fast Food',
        brand: 'Brand',
        individual_collection: 'Individual Collection',
        cocola: 'Cocola',
        ifad: 'Ifad',
        kazi_farmas: 'Kazi Farmas∂',
        apply_filter: 'Apply Filter',
    },
    addCart: {
        go_to_checkout: 'Go to Checkout'
    },
    favourite: {
        add_all_to_cart: 'Add All To Cart'
    }
}