export const AppScreens = {
    OnBoardingScreen: 'OnBoardingScreen',
    SignInScreen: 'SignInScreen',
    VerificationScreen: 'VerificationScreen',
    SelectLocationScreen: 'SelectLocationScreen',
    logInScreen: 'LogInScreen',
    SignUpScreen: 'SignUpScreen',
    HomeScreen: 'HomeScreen',
    BottomTab: 'BottomTab',
    ExploreProductScreen: 'ExploreProductScreen',
    MyCartScreen: 'MyCartScreen',
    FavouriteScreen: 'FavouriteScreen',
    AccountScreen: 'AccountScreen',
    ProductDetailScreen: 'ProductDetailScreen',
    AppNavigator: 'AppNavigator',
    HomeStackNavigation: 'HomeStackNavigation',
    AllProductScreen: 'AllProductScreen',
    ExploreStackNavigation: 'ExploreStackNavigation',
    FilterScreen: 'FilterScreen',
    FilteredDataScreen: 'FilteredDataScreen',
    ApiCallUsingFetch: 'ApiCallUsingFetch',
    Pagination: 'Pagination',
    AuthStack: 'AuthStack',
    ReduxDemo: 'ReduxDemo',
    ApiCallUsingRedux: 'ApiCallUsingRedux',
    ReduxToolkit: 'ReduxToolkit',
    ApiCallUsingReduxToolkit: 'ApiCallUsingReduxToolkit',
    FirebaseDemo: 'FirebaseDemo',
    CloudFireStore: 'CloudFireStore',
    CloudStorage: 'CloudStorage',

}